version: '3.7'

services:
  torchserver:
    image: emlo:s19
    shm_size: '1gb'
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "7070:7070"
      - "7071:7071"
